#!/usr/bin/env bash
# Transfers a file from Holberton's client to another.
# Accepts four arguments:
# The file path of the file to transferred.
# The server IP of the server to destination of the file.
# The username used for scp connection.
# The path to the SSH private key used by scp.

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
