#!/usr/bin/env bash
# Instructions for installing Nginx on a web server.

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#Checking the configurations of Nginx for any issues or errors.
sudo ngix -t

sudo service nginx start
