#!/usr/bin/env bash
# Instructions for installing Nginx on Web-Sever-01

# Ensuring Packages are up to date before proceeding with Installations
sudo apt-get -y update
sudo apt-get -y install nginx

# Setting up the Uncomplicated Firewall (UFW) to permit incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Crafting an index.html page
echo 'Hello World!' > /var/www/html/index.html

# Restarting Nginx
sudo service nginx start
