#!/usr/bin/env bash
# Sets up an Nginx server to listen specifically on port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
