#!/usr/bin/env bash
# Showcase a list of processes that are currently running.
# Display list of all processes, regards all users, including
# those that may not have a terminal TTY associated with them.

ps -auxf
