#!/usr/bin/env bash
# Displays the phrase "To infinity and beyond"repeatedly, and
# after each display,it wait for 2 seconds before next iteration.
# Displays "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
